chore: Update test1.yml and test2.yml workflows to handle failure in extracting Expo URL

diff --git a/.github/workflows/test1.yml b/.github/workflows/test1.yml
--- a/.github/workflows/test1.yml
+++ b/.github/workflows/test1.yml
@@ -50,6 +50,10 @@ jobs:
     - name: Extract Expo URL
       run: |
         expo_url=$(grep -oP '(?<=URL: ).*' expo.log | tail -n 1)
+        if [ -z "$expo_url" ]; then
+          echo "Failed to extract Expo URL"
+          exit 1
+        fi
         echo "EXPO_URL=$expo_url" >> $GITHUB_ENV
     - name: Display Expo URL
       run: |
diff --git a/.github/workflows/test2.yml b/.github/workflows/test2.yml
--- a/.github/workflows/test2.yml
+++ b/.github/workflows/test2.yml
@@ -50,7 +50,11 @@ jobs:
     - name: Extract Expo URL
       run: |
         expo_url=$(grep -oP '(?<=URL: ).*' expo.log | tail -n 1)
-        echo "EXPO_URL=$expo_url" >> $GITHUB_ENV
+          if [ -z "$expo_url" ]; then
+            echo "Failed to extract Expo URL"
+            exit 1
+          fi
+          echo "EXPO_URL=$expo_url" >> $GITHUB_ENV
     - name: Display Expo URL
       run: |
         echo "Expo URL: ${{ env.EXPO_URL }}"
